#+TITLE: Tedward Erker
#+AUTHOR: Tedward Erker
#+OPTIONS: toc:nil num:nil
#+STARTUP: entitiespretty
#+LATEX_CLASS: moderncv
#+LATEX_HEADER: \moderncvstyle{classic}
#+LATEX_HEADER: \moderncvcolor{blue}
#+LATEX_HEADER: \usepackage[scale=0.75]{geometry}
#+LATEX_HEADER: \name{Tedward}{Erker}
#+LATEX_HEADER:
#+LATEX_HEADER:
#+LATEX_HEADER:
#+LATEX_HEADER:
#+LATEX_HEADER:
* Summary of Qualifications and Skills

Biometry M.S. and Forestry Ph.D. (expected spring 2019) with 5 years
of research and data analysis experience and 2 years of high school
teaching experience.  Comfortable with a wide range of statistical
methods including generalized linear models and tree-based
methods. Driven to understand complex problems and distill key
findings for nonexpert audiences via fully reproducible reports and
compelling figures.  Independently motivated. A positive, constructive
team member and leader.  Passionate about working in education.
** COMMENT

Statistical methods I have implemented: GLMs, GAMs, mixed effects/
multilevel models, partial least squares regression, elastic net, principal
components analysis, random forests, support vector machines, boosted
regression trees.


GLMs, GAMs, shrinkage and dimension reduction,
tree-based methods, and working with dependent data and large datasets
in R.


shrinkage methods, high dimension, large data, dependent data.  some bayesian.

Computing: Daily use of R, familiarity with python and Stan.

R
familiarity with other languages (Python and Stan).

reproducible research git

science

statistics

making figures

writing

background in education

manage undergraduates

independent work but also part of a team.

deadlines.

coursework

web scraping

writing - papers, proposals ($money), presentations

1 paper in review; over $150k in proposals

* Education
** Sep 2013 - Present
*Ph.D. Forestry* \\
Department of Forest and Wildlife Ecology, University of Wisconsin--Madison \\
GPA: 3.929

** Sep 2013 - Present
*M.S. Biometry* \\
Department of Statistics, University of Wisconsin--Madison

** Aug 2006 - May 2008 & Aug 2009 - May 2010
*B.A. Environmental Studies--Ecology/Biology* \\
Summa Cum Laude, Washington University in St. Louis \\
GPA: 3.83

** COMMENT Activities (probably no point in including undergrad activities).
Activities: [[http://outing.wustl.edu/WildernessProject/philosophy.html][Wilderness Project]] Freshman Orientation Program. Founder
of [[http://burningkumquat.wustl.edu/][The Burning Kumquat]], the campus vegetable garden.
** COMMENT Old way of printing Education

- Ph.D, [[http://forestandwildlifeecology.wisc.edu/graduate-study-forestry-handbook][Forestry]], University of Wisconsin - Madison, 2013--.

Committee: Phil Townsend (advisor), Jun Zhu, Chris Kucharik, Eric Kruger,
  Annemarie Schneider.

- M.S., [[https://www.stat.wisc.edu/masters-biometry][Biometry]], University of Wisconsin--Madison, 2013--.
- B.A., [[https://enst.wustl.edu/programs][Environmental Studies]]--Ecology/Biology, Summa Cum Laude, Washington University
  in St. Louis, 2006/8-2008/5, 2009/8-2010/5.  GPA: 3.83
