* Teaching Experience
** Spring 2015
*Statistical Methods for Bioscience II Teaching Assistant*

Led 2 weekly discussion groups, graded homework and exams for this
graduate-level course. Prof. Murray Clayton.

** Fall 2013 and Fall 2015
*Forest Ecology Teaching Assistant*

Redesigned, created and independently implemented lab lessons in field and computer lab for ~70
students.  Prof. Tom Gower (2013) and Prof. Phil Townsend (2015).

** Spring 2014
*Living With Wildlife Teaching Assistant*

Graded journals and exams, assisted students during office hours.
Prof. Stan Temple.

** August 2010 - May 2012
*High School Chemistry and Biology Teacher*

Educated over 120 students in six classes daily. As first year
teacher, developed chemistry curriculum for new charter school
integrating College Readiness Standards with Missouri Science
Standards. Cross-country coach. [[https://www.google.com/search?q=Confluence+Preparatory+Academy+St.+Louis&oq=Confluence+Prep+Academy+St.+Louis&aqs=chrome..69i57.7294j0j8&sourceid=chrome&ie=UTF-8#q=Confluence+Prep+Academy+High+School+St.+Louis][Confluence Preparatory Academy]]. St. Louis, MO.

** June 2010 - May 2012
*[[https://www.teachforamerica.org/][Teach For America]] Corps Member*

Selected from over 46,000 applicants nationwide to join the national
teacher corps of recent college graduates who commit two years to
teach in under-resourced public schools.  Chicago, IL & St. Louis, MO.

** Spring 2008
*Undergraduate Teaching Assistant*

Brave New Crops, Environmental Studies 3322. Professor Glenn Davis
Stone. Washington University in St. Louis.
