#+TITLE: Tedward Erker
#+AUTHOR: Tedward Erker
#+KEYWORDS: vita, CV, resume
#+OPTIONS: toc:nil num:nil
#+STARTUP: entitiespretty
#+LaTeX_HEADER: \usepackage{fa_orgmode_cv}
* COMMENT Navigating "included" files: C-' visits file at point
* Contact Information
#+ATTR_HTML: :frame void
#+ATTR_LATEX: :environment tabular :align rp{0.85\textwidth}
|      <r> |                                     |
|   Phone: | 314-324-6079                        |
|   Email: | [[mailto:erker@wisc.edu][tedward.erker@gmail.com]]             |
|     Web: | [[http://pages.stat.wisc.edu/~erker/][pages.stat.wisc.edu/~erker]]          |
|  github: | [[https://github.com/tedwarderker][github.com/tedwarderker]]             |
| address: | 425 N Baldwin St, Madison, WI 53703 |


* Summary of Qualifications and Skills
#+LATEX: {\leftskip=0.02\textwidth
Biometry M.S. and Forestry Ph.D. (expected spring 2019) with 5 years
of research and data analysis experience and 2 years of high school
teaching experience.  Comfortable with a wide range of statistical
methods including generalized linear models and tree-based
methods. Driven to understand complex problems and distill key
findings for nonexpert audiences via fully reproducible reports and
compelling figures.  Independently motivated. A positive, constructive
team member and leader.  Passionate about working in education.
#+LATEX: \par}
** COMMENT

Statistical methods I have implemented: GLMs, GAMs, mixed effects/
multilevel models, partial least squares regression, elastic net, principal
components analysis, random forests, support vector machines, boosted
regression trees.


GLMs, GAMs, shrinkage and dimension reduction,
tree-based methods, and working with dependent data and large datasets
in R.


shrinkage methods, high dimension, large data, dependent data.  some bayesian.

Computing: Daily use of R, familiarity with python and Stan.

R
familiarity with other languages (Python and Stan).

reproducible research git

science

statistics

making figures

writing

background in education

manage undergraduates

independent work but also part of a team.

deadlines.

coursework

web scraping

writing - papers, proposals ($money), presentations

* Education
** Sep 2013 - Present
*Ph.D. Forestry* \\
Department of Forest and Wildlife Ecology, University of Wisconsin--Madison \\
GPA: 3.929

** Sep 2013 - Present
*M.S. Biometry* \\
Department of Statistics, University of Wisconsin--Madison

** Aug 2006 - May 2008 & Aug 2009 - May 2010
*B.A. Environmental Studies--Ecology/Biology* \\
Summa Cum Laude, Washington University in St. Louis \\
GPA: 3.83

** COMMENT Activities (probably no point in including undergrad activities).
Activities: [[http://outing.wustl.edu/WildernessProject/philosophy.html][Wilderness Project]] Freshman Orientation Program. Founder
of [[http://burningkumquat.wustl.edu/][The Burning Kumquat]], the campus vegetable garden.
** COMMENT Old way of printing Education

- Ph.D, [[http://forestandwildlifeecology.wisc.edu/graduate-study-forestry-handbook][Forestry]], University of Wisconsin - Madison, 2013--.

Committee: Phil Townsend (advisor), Jun Zhu, Chris Kucharik, Eric Kruger,
  Annemarie Schneider.

- M.S., [[https://www.stat.wisc.edu/masters-biometry][Biometry]], University of Wisconsin--Madison, 2013--.
- B.A., [[https://enst.wustl.edu/programs][Environmental Studies]]--Ecology/Biology, Summa Cum Laude, Washington University
  in St. Louis, 2006/8-2008/5, 2009/8-2010/5.  GPA: 3.83
* Relevant graduate coursework
| Tools for Reproducible Research      | Advanced Data Analysis with R             |
| Statistical Methods-Spatial Data     | Multilevel Models                         |
| Intro Mathematical Statistics I & II | Statistical Methods for Bioscience I & II |
| Teaching Statistics                  | Inquiry-Based Biology Teaching            |

* awards and fellowships                                             :ignore:
#+INCLUDE: awards_fellowships.org :minlevel 1
* Scientific Presentations and Posters                               :ignore:
#+INCLUDE: presentations.org :minlevel 1
#+INCLUDE: posters.org :minlevel 1
* Teaching Experience                                                :ignore:
#+INCLUDE: teaching_experience.org :minlevel 1
* Mentoring                                                  :ignore:
#+INCLUDE: mentoring.org :minlevel 1
* Relevant Work Experience                                           :ignore:
#+INCLUDE: work_experience.org :minlevel 1
* Professional Affiliations
Society of American Foresters, 2016--Present

* Languages
Spoken: English, Spanish

Computing: R

* Service to the Department and University
** Oct 2015 - Present
*Graduate Student Representative, Department of Forest and Wildlife
Ecology*
*** COMMENT details
- I represent graduate student interests at monthly department
  meetings, communicate relevant departmental changes to fellow
  graduate students, and organize professional development events and
  the weekly department social.
** Jul 2017
*Software Carpentry Volunteer*
*** COMMENT details
- Software Carpentry is a workshop designed to teach basic computing
  skills to researchers
- I volunteered two days to help teach graduate students the basics of
  the command line, version control (git), and python.

* Service to Community
**  Fall 2014 and Fall 2015
*Guest Lab Instructor, Sustainability by the Numbers, Shabazz High School*

*** COMMENT details
- Twice, I conducted a two day lab exercise in a sustainability
  oriented math class exploring the potential for urban trees to offset carbon emissions.

- Each year, I conducted a 2 day lab for about 20 students in a math class focused on
  sustainability at Malcolm Shabazz City High school, an alternative
  high school in Madison.
- The lab consisted of identifying the species and measuring the
  diameter at breast height of all the trees on the school's
  campus.  Students then used allometric equations to predict carbon storage and
  sequestration by trees, and compared this carbon to the carbon emitted by
  student to determine how many trees would be required to offset
  their emissions.
** Fall 2017
*Guest Lab Instructor, AP Environmental Studies, East High School*


*** COMMENT details
- I assisted with a field trip to the Madison School Forest for 85
  students in the AP environmental studies class at Madison East High
  School.
- Students used a clinometer and diameter at breast height tape to
  measure forest trees, they estimated carbon content of the trees,
  and they compared this to the carbon emissions caused by their
  transportation to and from school.

* Graduate Coursework                                                :ignore:
#+INCLUDE:graduate_coursework.org :minlevel 1

* COMMENT how to cv
https://github.com/fasheng/orgmode-latex-cv
#+LATEX_HEADER:\def\myemail{xavier.garrido@lal.in2p3.fr}
#+LATEX_HEADER:\def\myweb{stat.wisc.edu/~erker}
#+LATEX_HEADER:\def\myphone{+33 (0)1 64 46 84 28}

put fa\under{}orgmode\under{}cv.sty in ~/Library/texmf/tex/latex







* COMMENT workshops?
Andrew Finley's spBayes workshop
