* Relevant Work Experience

** August 2013 - December 2014
*Arborist*

Worked part time as ground crew, hauling brush and aiding climber.
Developed online Wisconsin tree species identification application.
[[http://www.urbantreealliance.org/][Urban Tree Alliance]], Non-profit. Madison, WI.

** February 2013 - August 2013
*Arborist*

Performed ground crew work, climbed, and as certified pesticide
applicator treated for a number of pests including the emerald ash
borer. [[http://atetreecare.com/][American Tree Experts]].  New Berlin, WI

** March 2007 - May 2010
*Greenhouse Assistant*

Water, transplant, propagate plants; maintain greenhouse. Work-Study
at [[http://biology4.wustl.edu/greenhouse/index.html][Washington University Plant Research Facility]]. St. Louis, MO.

** April - August 2009
*Farm Education Intern and Farmer*

Organized and guided trips of 16-40 students at farm and wilderness
education center. Managed 3⁄4 acre garden and cared for sheep, goats,
chickens, pigs, and cows as part of farm team.  [[https://farmandwilderness.org/][Farm And Wilderness
Summer Camps]]. Plymouth, VT.

** May - August 2008
*Research Assistant*

Sampled vegetation, identified over 100 plant species as part of study
to explore phylogenic relationships in invasiveness.  Tyson Research
Center. Eureka, MO.

